### ISSUE TITLE
Move to the Minetest Mods organization

### ISSUE THREAD

**Issue by Panquesito7** [bousket/unified_inventory_plus#11]
See https://minetest-mods.github.io/ for more information. 🙂

**Comment by fluxionary** [comment]
I'd like this to happen as well, and can start the process if @bousket signs off on it.

**Comment by bousket** [comment]
Sorry for the late answer. Of course fluxionary, feel free to change the code and make pull requests.

**Comment by fluxionary** [comment]
@bousket 

Could you "transfer" this mod to the mt-mods organization? https://github.com/mt-mods

It is like minetest-mods, but it is more actively maintained these days, and I am a part of it. 

You can find the "transfer" option in the settings, towards the bottom: https://github.com/bousket/unified_inventory_plus/settings

**Comment by bousket** [comment]
I could.

Why do you need a transfert?
What are the benefits ?


Le jeu. 14 avr. 2022 à 20:39, fluxionary ***@***.***> a
écrit :

**Comment by fluxionary** [comment]
The benefits would be for you - you have said you no longer have time to maintain this mod, and this would let the people who use and develop it to process updates to it easier, without having to bother you to click the "merge" button.

If you want to hold onto it, that is fine as well, but you should say so and close this issue :)

**Comment by bousket** [comment]
I will merge pull requests for now.
