### ISSUE TITLE
Allow to lock recipe slots

### ISSUE THREAD

**Issue by mk-pmb** [bousket/unified_inventory_plus#13]
Hi! I'd like a way to lock recipe slots. The easy part is for empty slots: I'd like to click them to toggle whether they shall refuse to accept items. This way I could lock the middle column, then shift-click 4 stacks of wood in my inventory and have the recipe for 99 wooden boots. It's independent of materials: After crafting them, I can then shift-click 4 stacks of steel ingots and have the recipe for 99 steel boots.

The harder part is that I'd like to lock recipe slots and/or the entire recipe, so that after they're crafted away, a ghost image of the items remains. It does not interfere with manual item placement, but shift-click on inventory items will prefer to fill into same-item ghost slots rather than the next empty slot.

**Comment by bousket** [comment]
Hi !
I dont work anymore on this project.
Feel free to implement functionnalities and propose merge.
I ll add it to the project and add you to contributors

**Comment by mk-pmb** [comment]
Thanks! I hope someone else will implement it, because I won't be able to do it soon.
