### ISSUE TITLE
futil and fmods

### ISSUE THREAD

**Issue by waxtatect** [bousket/unified_inventory_plus#24]
With last commits, 2 new mods became mandatory dependencies: futil and fmods (https://github.com/fluxionary/minetest-futil, https://github.com/fluxionary/minetest-fmod) and only used through futil with those: futil.check_version and futil.FakeInventory

Would it be possible that futil is optional? and update readme so one can choose, thanks

**Comment by wsor4035** [comment]
seems like a wasteful deps that should be removed tbh.

**Comment by fluxionary** [comment]
wasteful? the need for using FakeInventory is explained in #23.

**Comment by S-S-X** [comment]
Seems like simple solution would be to directly include needed/wanted part (after little cleanup) here or reimplement it here, actual required thing is really simple after all.

**Comment by fluxionary** [comment]
> Seems like simple solution would be to directly include needed/wanted part (after little cleanup) here or reimplement it here, actual required thing is really simple after all.

and then it has to be maintained in multiple places. i've fixed bugs in FakeInventory before.

**Comment by S-S-X** [comment]
> and then it has to be maintained in multiple places. i've fixed bugs in FakeInventory before.

Like many things yes, I could also suggest optionally breaking it out from minetest-fmod and providing minetest-fakeinventory mod and having that as dependency but I guess that wont exactly go well with minetest-fmod plans?

edit. or I think it was that other mod, anyway whichever it is. other one seems to provide just version table which seems good as it seems to do one specific thing.

**Comment by fluxionary** [comment]
my goal is to make futil an actual library mod - it doesn't do anything except provide useful functions that i regularly use. the exception to this intention is currently in providing a list of items belonging to a group, which could instead be calculated at runtime, if anyone objects. see https://github.com/fluxionary/minetest-futil/blob/7048be0b7b2cf3dded7241ebe0c733dbf8fd1085/minetest/group.lua#L45-L61

i've also switched from using the AGPL to the LGPL for my mods recently, if that's a point of contention, it's no longer relevant.

> I could also suggest optionally breaking it out from minetest-fmod and providing minetest-fakeinventory mod 

i'd rather not provide a separate mod for every function in futil, but i'm not totally opposed to the idea. perhaps it could instead become a modpack. i'm interested to hear what other people think.

**Comment by SwissalpS** [comment]
while I like your efforts with futil, I have to agree that the relative small portion it is used for, is a bit overkill. (see recent pipeworks:autocrafter update that solved the issue with a few lines without the need of loading a full fledged class that copies entire inventory instead of just the list that is actually being processed)

**Comment by fluxionary** [comment]
> while I like your efforts with futil, I have to agree that the relative small portion it is used for, is a bit overkill. (see recent pipeworks:autocrafter update that solved the issue with a few lines without the need of loading a full fledged class that copies entire inventory instead of just the list that is actually being processed)

if someone wants to write up a solution that gets rid of futil, i won't be offended. but note that the code in question is more complicated than what's currently in pipeworks - it calls `minetest.on_craft`, which needs an argument that "acts like" a full inventory object. note that pipeworks should be invoking that callback as well, see https://github.com/mt-mods/pipeworks/issues/67.
