### ISSUE TITLE
Crash with unified_inventory 20191017

### ISSUE THREAD

**Issue by redblade7** [bousket/unified_inventory_plus#5]
The latest version of unified_inventory (20191017) causes unified_inventory_plus to crash the server when the first player joins:

> 2019-10-18 14:54:32: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback on_joinplayer(): .../minetest_game/mods/unified_inventory_plus/craft_all.lua:14: attempt to call upvalue 'S' (a nil value)
> 2019-10-18 14:54:32: ERROR[Main]: stack traceback:
> 2019-10-18 14:54:32: ERROR[Main]:       .../minetest_game/mods/unified_inventory_plus/craft_all.lua:14: in function 'craft_organize'
> 2019-10-18 14:54:32: ERROR[Main]:       ...test_game/mods/unified_inventory_plus/craft_organize.lua:11: in function 'craft_rotate'
> 2019-10-18 14:54:32: ERROR[Main]:       ...netest_game/mods/unified_inventory_plus/craft_rotate.lua:11: in function 'get_formspec'
> 2019-10-18 14:54:32: ERROR[Main]:       .../games/minetest_game/mods/unified_inventory/internal.lua:84: in function 'get_formspec'
> 2019-10-18 14:54:32: ERROR[Main]:       .../games/minetest_game/mods/unified_inventory/internal.lua:270: in function 'set_inventory_formspec'
> 2019-10-18 14:54:32: ERROR[Main]:       ...games/minetest_game/mods/unified_inventory/callbacks.lua:25: in function <...games/minetest_game/mods/unified_inventory/callbacks.lua:12>
> 2019-10-18 14:54:32: ERROR[Main]:       (REMOVED)/bin/../builtin/game/register.lua:429: in function <(REMOVED)/bin/../builtin/game/register.lua:413>

**Comment by thomasrudin** [comment]
Oh, thats bad: it is calling a function of unified_inv which is not there since https://github.com/minetest-mods/unified_inventory/commit/53272617184bbe3cca16101e14c4e4f3ea54467e

**Comment by bousket** [comment]
It should be fixed now. Try it out and come back if it s not.
