### ISSUE TITLE
Using "craft all" on recipes w/ replacements loses all the replacements.

### ISSUE THREAD

**Issue by fluxionary** [bousket/unified_inventory_plus#6]
Using "craft all" on recipes w/ replacements loses all the replacements. In truth, when the last craft is done, because the crafting grid is now empty, a replacement will go there, but all the other replacements are just ignored and lost.

**Comment by bousket** [comment]
I don t understand. Can you provide me a real example ?

Le mar. 24 déc. 2019 à 20:46, fluxionary <notifications@github.com> a
écrit :

**Comment by fluxionary** [comment]
documentation on recipe replacements:
* https://github.com/minetest/minetest/blob/44458896d9097c15c722c5bffb3d72e14962b7ce/doc/lua_api.txt#L6856

documentation on where replacements show up after get_craft_results:
* https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4785

For an example of where this matters, lets use the recipe for ciabatta dough from [Cucina Vegana](https://forum.minetest.net/viewtopic.php?t=20001). Note that Cucina Vegana has a bunch of other recipes w/ replacements, but some of those aren't specified sanely, so just use this one for reference.
![screenshot_20191225_151239](https://user-images.githubusercontent.com/25628292/71447682-764b2500-2729-11ea-9260-76a29f6c175c.png)

The recipe contains the following:
* Soy milk
* Sunflower seed oil
* Flour
* Rosemary

[The recipe specifies](https://github.com/acmgit/cucina_vegana/blob/3f3877598d1983effc6f1035d65470a5806a5355/recipes.lua#L37) that the soy milk will be replaced with a drinking glass, and the oil w/ a bottle. As you can see, if I craft one item, the replacements show up in the crafting grid:

![screenshot_20191225_151253](https://user-images.githubusercontent.com/25628292/71447683-7b0fd900-2729-11ea-9891-77ff0bcfc655.png)

However, there are problems if I try to craft things in bulk using the `all` button from this mod:

![screenshot_20191225_151028](https://user-images.githubusercontent.com/25628292/71447686-8105ba00-2729-11ea-9570-7c119f51444f.png)
![screenshot_20191225_151151](https://user-images.githubusercontent.com/25628292/71447690-87943180-2729-11ea-9408-96d9533198bf.png)

From what I can understand, the replacement items are only automatically placed in the crafting grid, if nothing is left in the grid after crafting. Otherwise, the mod code has to manually handle doing something w/ the replacements.

**Comment by fluxionary** [comment]
Also there's a bug in the game engine that's making it tricky for me to come up w/ a good resolution. See https://github.com/minetest/minetest/issues/9250

**Comment by bousket** [comment]
ok now I understand. I have to take time to fully understand the concept
and I ll fix it.

Le mer. 25 déc. 2019 à 16:28, fluxionary <notifications@github.com> a
écrit :

**Comment by Golutazem** [comment]
Is this related to the 
[bug of Craft All making products which should be colored white](https://gitlab.com/VanessaE/coloredwood/-/issues/2) ?

**Comment by fluxionary** [comment]
@Golutazem no, I think that's a separate issue for items w/ metadata
