### ISSUE TITLE
 Item damage get's zero'ed on sorting in creator

### ISSUE THREAD

**Issue by norpol** [bousket/unified_inventory_plus#8]
If you put a single item (such as a axe) into the creator and then hit one of the sorting buttons, the item will lose it's damage information and be fully functional again. Same happens to things that are battery powered, but in this case the battery becomes empty. Sorry if I'm not using the correct terminology, I hope this is enough information for reproducing the bug.

![screenshot-2020-02-28T01:14:26+01:00](https://user-images.githubusercontent.com/2230917/75498606-e3986200-59c7-11ea-8843-07dc64b56a24.png)
![screenshot-2020-02-28T01:14:21+01:00](https://user-images.githubusercontent.com/2230917/75498608-e5622580-59c7-11ea-9286-4cc4b258e568.png)

**Comment by BuckarooBanzay** [comment]
Looks like this is caused by this:
https://github.com/bousket/unified_inventory_plus/blob/2b09f0f0a025f3185c27af6813735a14f911a2a9/craft_organize.lua#L86

The "wear" data is ignored in this case...

**Comment by fluxionary** [comment]
Note: all item metadata also gets wiped.
